[package]
name = "rsvart"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.18.2"
cargo-tarpaulin = "0.27.3"
